config/routes.rb
Rails.application.routes.draw do
 root to: 'users#index'
 
 get 'signup', to: 'users#new'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
 resources :companies
 resources :recruits, only: [:show, :new, :create, :edit, :update, :destroy]
 resources :members, only: [:show, :new, :create, :edit, :update, :destroy]
 resources :users
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum:50 }
  validates :sex, presence: {message: 'にチェックしてください'}
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :birthday, presence: true
  validates :password, length: { minimum:6, maximum:12 }
  validate :correct_image_mime_type
  validate :correct_resume_file_mime_type
  validate :correct_career_file_mime_type
  validates :accepted, presence: {message: 'にチェックしてください'}
  
  has_many :user_tag_relations, dependent: :destroy
  has_many :tag, through: :user_tag_relations
  
  belongs_to :prefecture, optional: true
      
  has_secure_password
  has_one_attached :image
  has_one_attached :resume_file
  has_one_attached :career_file

  def self.search(keyword)
    if keyword && keyword != ""
      words = keyword.to_s.split(" ")
      columns = ["selfpr", "academic_background", "certification"]
      query = []
      result = []
 
      columns.each do |column|
        query << ["#{column} LIKE ?"]
      end
 
      words.each_with_index do |w, index|
        if index == 0
          result[index] = User.where([query.join(" OR "), "%#{w}%", "%#{w}%", "%#{w}%"])
        else
          result[index] = result[index-1].where([query.join(" OR "), "%#{w}%", "%#{w}%", "%#{w}%"])
        end
      end
      return result[words.length-1]
    else
      User.all
    end
  end
  
  def age()
    now = Time.zone.now
    date_format = "%Y%m%d"
    (now.strftime(date_format).to_i - self.birthday.strftime(date_format).to_i) / 10000
  end
  
  private
  def correct_image_mime_type
    if image.attached? && !image.content_type.in?(%w(image/jpg image/jpeg image/png))
      errors.add(:image, 'を入れて下さい')
    end
  end

  def correct_resume_file_mime_type
    if resume_file.attached? && !resume_file.content_type.in?(%w(application/pdf))
      errors.add(:resume_file, 'を入れて下さい')
    end
  end
  
  def correct_career_file_mime_type
    if career_file.attached? && !career_file.content_type.in?(%w(application/pdf))
      errors.add(:career_file, 'を入れて下さい')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
      if params[:search].present?
        if params[:prefecture_id].present? && params[:search].present?
          @users = @users.where(prefecture_id: params[:prefecture_id]).search(params[:search])
        elsif params[:sex].present? && params[:search].present?
          @users = @users.where(sex: params[:sex]).search(params[:search])
        elsif params[:tag_id].present? && params[:search].present?
          @users = Tag.find(params[:tag_id]).users.search(params[:search])
        elsif params[:search].present?
          @users = @users.search(params[:search])
        end
      elsif params[:prefecture_id].present?
        if params[:sex].present? && params[:prefecture_id].present?
          @users = @users.where(sex: params[:sex]).where(prefecture_id: params[:prefecture_id])
        elsif params[:tag_id].present? && params[:prefecture_id].present?
          @users = Tag.find(params[:tag_id]).users.where(prefecture_id: params[:prefecture_id])
        elsif params[:prefecture_id].present?
          @users = @users.where(prefecture_id: params[:prefecture_id])
        end
      elsif params[:sex].present?
        if params[:tag_id].present? && params[:sex].present?
          @users = Tag.find(params[:tag_id]).users.where(sex: params[:sex])
        elsif params[:sex].present?
          @users = @users.search(params[:search])
        end
      elsif params[:tag_id].present?
        if params[:tag_id].present?
          @users = Tag.find(params[:tag_id]).users
        end
      end
      
    @users = @users.page(params[:page]).order('created_at DESC').per(5)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = '転職希望者を登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = '転職希望者の登録に失敗しました。'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = "転職希望者情報を更新しました"
      redirect_to @user
    else
      flash.now[:danger] = "転職希望者情報を更新できませんでした"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:success] = "転職希望者を削除しました"
    redirect_to "/users"
  end
  
  private
  
  def user_params
    params.require(:user).permit(:image, :name, :sex, :birthday, :address, :telephone, :email, :academic_background, :resume_file, :career_file, :password, :password_confirmation, :age, :accepted, :selfpr, :prefecture_id, :certification, tag_ids: [])
  end
  
end

app/views/users/edit.html.erb
<%= link_to "戻る", @user, class: "btn btn-outline-secondary btn-circle" %>
<h1>転職希望者情報編集</h1>
<p>* 入力必須項目</p>

<%= form_for(@user) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
<div class="card">
  <div class="card-body">
    <h3 class="card-title">プロフィール(基本情報)</h3><p>* 入力必須項目</p>
      <table class="table">
      <tbody>
        <tr>
          <th style="width:20%"><i class="fas fa-camera"></i> 履歴書写真</th>
          <td>
            <div class="form-group">
              <%= f.file_field :image, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th style="width:20%"><i class="fas fa-user-alt"></i> 氏名 *</th>
          <td>
            <div class="form-group">
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-venus-mars"></i> 性別 *</th>
          <td>
            <div class="form-group">
              <div class="sex btn-group" data-toggle="buttons">
                <label class="btn btn-outline-secondary" style="width:50%">
                  <%= f.radio_button :sex, "男性" %> 男性
                </label>
                <label class="btn btn-outline-secondary" style="width:50%">
                  <%= f.radio_button :sex, "女性" %> 女性
                </label>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-birthday-cake"></i> 生年月日</th>
          <td>
            <div class="row">
              <div class="col-md">
                <div class="form-inline">
                  <%= raw sprintf(
                              f.date_select(
                                :birthday,
                                {
                                  use_month_numbers: true,
                                  start_year: 1930,
                                  end_year: (Time.now.year - 18),
                                  default: Date.new(1989, 1, 1),
                                  date_separator: '%s'
                                },
                                { class: 'form-control col-md-3' }
                              ),
                              '年 ', '月 ') + '日' %>
                </div>
              </div>
              <div class="col-md">
                <%= f.number_field :age, disabled: true, class: "form-control", style: "width:30%" %>
              </div>
            </div>

          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-map-marker-alt"></i> 現住所</th>
          <td>
            <div class="form-group">
              <div class="row">
                <div class="col-md-2">
                  <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: '選択して下さい'}, { class: "form-control" } %>
                </div>
                <div class="col-md-10">
                  <%= f.text_field :address, class: "form-control form-inline", placeholder: "市区町村,番地等をいれて下さい" %>
                </div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-phone"></i> 電話番号</th>
          <td>
            <div class="form-group">
              <%= f.text_field :telephone, class: "form-control" %> 
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-envelope"></i> メールアドレス *</th>
          <td>
            <div class="form-group">
              <%= f.email_field :email, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-user-graduate"></i> 最終学歴</th>
          <td>
            <div class="form-group">
              <%= f.text_field :academic_background, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-award"></i> 資格</th>
          <td>
            <div class="form-group">
              <%= f.text_area :certification, class: "form-control", rows: 3, placeholder: 'オラクルマスターゴールド／日商簿記検定1級／秘書検定1級等、資格を続けてご記入ください'  %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-wrench"></i> スキル</th>
          <td>  
            <div class="form-group">
              <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                <div class="form-check form-check-inline">
                  <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-file-pdf"></i> 履歴書ファイル</th>
          <td>
            <div class="form-group">
              <%= f.file_field :resume_file, class: "form-control" %>
            </div>  
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-file-pdf"></i> 職務経歴書ファイル</th>
          <td>
            <div class="form-group">
              <%= f.file_field :career_file, class: "form-control" %>
            </div>   
          </td>
        </tr>
        <tr>
          <th scope="row">パスワード * <br>(6文字以上12文字以下)</th>
          <td>
            <div class="form-group">
              <%= f.password_field :password, class: 'form-control' %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">パスワード確認</th>
          <td>
            <div class="form-group">
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">自己PR</th>
          <td>
            <div class="form-group">
              <%= f.text_area :selfpr, class: "form-control", rows: "10", placeholder: "今までの経験を活かして「こんな仕事ができる」「役に立てる」というイメージしやすさをうまく表現できると非常に効果的です。" %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
  <div class="form-last text-center">
    <div class="field">
      <%= f.check_box :accepted ,{},checked_value = "true",unchecked_value = "false" %>
      <%= f.label '内容の変更に同意する' %>
    </div>
    <%= f.submit '更新', class: "btn btn-outline-primary w-25" %>
  </div>
<% end %>

app/views/users/index.html.erb
<% if logged_in? %>
  <h1>
    転職希望者一覧
    <%= link_to "+ 新規転職希望者登録", signup_path, class: "btn btn-outline-primary align-items-center col-xs " %>
  </h1>
  
  <ul>
    <div class="container" id="search">
      <div class="row">
        <div class="col-md-2" id="pulldown">
          <div class="form-group">
            <%= form_tag users_path, method: :get, class: 'users__searchForm' do %>
              <%= select_tag :prefecture_id,
                             options_from_collection_for_select(Prefecture.all, :id, :name, params[:prefecture_id]),
                             {
                               prompt: '都道府県で絞り込み',
                               class: 'form-control users__select'
                             }
              %>
          </div>
        </div>
        <div class="col-md-2" id="pulldown">
          <div class="form-group">
            <%= form_tag users_path, method: :get, class: 'users__searchForm' do %>
              <%= select_tag :sex, options_for_select([["男性","男性"],["女性","女性"]], params[:sex]), prompt: '性別', class: 'form-control' %>
          </div>
        </div>
        <div class="col-md-2" id="pulldown">
          <div class="form-group">
            <%= form_tag users_path, method: :get, class: 'users__searchForm' do %>
              <%= select_tag :tag_id,
                             options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                             {
                               prompt: 'スキルで絞り込み',
                               class: 'form-control users__select'
                             }
              %>
          </div>
        </div>
        <div class="col-md-5">
          <%= text_field_tag :search, params[:search], placeholder: "キーワード 例)自己PR 学歴 資格 (複数入力時スペース半角)", class: 'form-control' %>
        </div>
        <div class="col-md-1" id="search-button">
          <%= submit_tag '検索', class: 'btn btn-primary', name: nil, academic_background: nil %>
        </div>
        <% end %>
        <% end %>
        <% end %>
      </div>
    </div>

    <% @users.each do |user| %>
      <li class="card-deck">
        <div class="card">
          <div class="card-body">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-lg-1">
                  <% if user.image.attached? %>
                    <%= image_tag user.image.variant(resize: "64x64!"), class: "img-thumbnail rounded-circle" %>
                  <% else %>
                    <%= image_tag "/person.png", class: "img-thumbnail rounded-circle" %>
                  <% end %>                
                </div>
                <div class="col-lg-2">
                  <%= user.name %>
                </div>
                <div class="col-lg-3">
                  <table>
                    <tbody>
                      <tr>
                        <th><i class="fas fa-venus-mars"></i></th>
                        <td><%= user.sex %></td>
                      </tr>
                      <tr>
                        <th><i class="fas fa-envelope"></i></th>
                        <td><%= user.email %></td>
                      </tr>
                      <% if user.academic_background.present? %>
                        <tr>
                          <th><i class="fas fa-user-graduate"></i></th>
                          <td><%= user.academic_background %></td>
                        </tr>
                      <% end %>
                      <% if user.certification.present? %>
                        <tr>
                          <th><i class="fas fa-award"></i></th>
                          <td><%= user.certification %></td>
                        </tr>
                      <% end %>
                      <% if user.prefecture.name.present? %>
                        <tr>
                          <th><i class="fas fa-map-marker-alt"></i></th>
                          <td><%= user.prefecture.name %></td>
                        </tr>
                      <% end %>
                      <% if user.tag.present? %>
                        <tr>
                          <th><i class="fas fa-wrench"></i></th>
                          <td>
                            <% user.tag.each do |tag| %>
                              <span class="badge badge-info"><%= tag.name %></span>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <div class="col-lg-4">
                  <% if user.selfpr.present? %>
                    <p>自己PR</p>
                    <p><%= user.selfpr %></p>
                  <% end %>
                </div>
                <div class="col-xs-1">
                  <%= link_to "詳細", user_path(user), class: "btn btn-outline-info" %>
                  <%= link_to "編集", edit_user_path(user), class: "btn btn-outline-info" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>
    <% end %>
    <%= paginate @users %>
  </ul>

<% else %>
  <%= render "sessions/login_form" %>
<% end %>

app/views/users/new.html.erb
<%= link_to "戻る", users_path, class: "btn btn-outline-secondary btn-circle" %>
<h1>新規転職希望者登録</h1>


<%= form_for(@user) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
<div class="card">
  <div class="card-body">
    <h3 class="card-title">プロフィール(基本情報)</h3><p>* 入力必須項目</p>
      <table class="table">
      <tbody>
        <tr>
          <th style="width:20%"><i class="fas fa-camera"></i> 履歴書写真</th>
          <td>
            <div class="form-group">
              <%= f.file_field :image, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th style="width:20%"><i class="fas fa-user-alt"></i> 氏名 *</th>
          <td>
            <div class="form-group">
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-venus-mars"></i> 性別 *</th>
          <td>
            <div class="form-group">
              <div class="sex btn-group" data-toggle="buttons">
                <label class="btn btn-outline-secondary" style="width:50%">
                  <%= f.radio_button :sex, "男性" %> 男性
                </label>
                <label class="btn btn-outline-secondary" style="width:50%">
                  <%= f.radio_button :sex, "女性" %> 女性
                </label>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-birthday-cake"></i> 生年月日</th>
          <td>
            <div class="form-inline col-md-6" id="birthday">
              <%= raw sprintf(
                          f.date_select(
                            :birthday,
                            {
                              use_month_numbers: true,
                              start_year: 1930,
                              end_year: (Time.now.year - 18),
                              default: Date.new(1989, 1, 1),
                              date_separator: '%s'
                            },
                            { class: 'form-control col-md-3' }
                          ),
                          '年 ', '月 ') + '日' %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-map-marker-alt"></i> 現住所</th>
          <td>
            <div class="form-group">
              <div class="row">
                <div class="col-md-2">
                  <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: '選択して下さい'}, { class: "form-control" } %>
                </div>
                <div class="col-md-10">
                  <%= f.text_field :address, class: "form-control form-inline", placeholder: "市区町村,番地等をいれて下さい" %>
                </div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-phone"></i> 電話番号</th>
          <td>
            <div class="form-group">
              <%= f.text_field :telephone, class: "form-control" %> 
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-envelope"></i> メールアドレス *</th>
          <td>
            <div class="form-group">
              <%= f.email_field :email, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-user-graduate"></i> 最終学歴</th>
          <td>
            <div class="form-group">
              <%= f.text_field :academic_background, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-award"></i> 資格</th>
          <td>
            <div class="form-group">
              <%= f.text_area :certification, class: "form-control", rows: 3, placeholder: 'オラクルマスターゴールド／日商簿記検定1級／秘書検定1級等、資格を続けてご記入ください'  %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-wrench"></i> スキル</th>
          <td>  
            <div class="form-group">
              <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                <div class="form-check form-check-inline">
                  <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-file-pdf"></i> 履歴書ファイル</th>
          <td>
            <div class="form-group">
              <%= f.file_field :resume_file, class: "form-control" %>
            </div>  
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-file-pdf"></i> 職務経歴書ファイル</th>
          <td>
            <div class="form-group">
              <%= f.file_field :career_file, class: "form-control" %>
            </div>   
          </td>
        </tr>
        <tr>
          <th scope="row">パスワード * <br>(6文字以上12文字以下)</th>
          <td>
            <div class="form-group">
              <%= f.password_field :password, class: 'form-control' %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">パスワード確認</th>
          <td>
            <div class="form-group">
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">自己PR</th>
          <td>
            <div class="form-group">
              <%= f.text_area :selfpr, class: "form-control", rows: "10", placeholder: "今までの経験を活かして「こんな仕事ができる」「役に立てる」というイメージしやすさをうまく表現できると非常に効果的です。" %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
  <div class="form-last text-center">
    <div class="field">
      <%= f.check_box :accepted ,{},checked_value = "true",unchecked_value = "false" %>
      <%= f.label '利用規約、及び、個人情報の取扱に同意する' %>
    </div>
    <%= f.submit '投稿', class: "btn btn-outline-primary w-25" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= link_to "戻る", users_path, class: "btn btn-outline-secondary btn-circle" %>
<h1>
  転職希望者詳細
  <%= link_to "編集", edit_user_path(@user), class: 'btn btn-outline-info' %>
  <%= link_to "削除", @user, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn btn-outline-danger' %>
</h1>

<div class="card">
  <div class="card-body">
    <h2 class="card-title"><%= @user.name %> | <%= @user.age %>歳 | <%= @user.prefecture.name if @user.prefecture_id.present? %></h2>
    <table class="table table-striped">
      <tbody>
        <tr>
          <th style="width:20%"><i class="fas fa-camera"></i> 履歴書写真</th>
          <td>
            <% if @user.image.attached? %>
              <%= image_tag @user.image.variant(resize: "100x100!"), class: "img-thumbnail" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th style="width:20%"><i class="fas fa-user-alt"></i> 氏名</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-venus-mars"></i> 性別</th>
          <td><%= @user.sex %></td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-birthday-cake"></i> 生年月日</th>
          <td><%= @user.birthday.strftime('%Y年%m月%d日') if @user.birthday.present? %> (<%= @user.age %>歳)</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-map-marker-alt"></i> 現住所</th>
          <td><%= @user.prefecture.name if @user.prefecture_id.present? %> <%= @user.address %></td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-phone"></i> 電話番号</th>
          <td><%= @user.telephone %></td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-envelope"></i> メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-user-graduate"></i> 最終学歴</th>
          <td><%= @user.academic_background %></td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-award"></i> 資格</th>
          <td><%= @user.certification %></td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-wrench"></i> スキル</th>
          <td>  
            <% @user.tag.each do |tag| %>
              <span class="badge badge-info"><%= tag.name %></span>
            <% end %>
          </td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-file-pdf"></i> 履歴書ファイル</th>
          <td><%= link_to "履歴書プレビュー", rails_blob_path(@user.resume_file, disposition: "resume_file") if @user.resume_file.attached? %></td>
        </tr>
        
        <tr>
          <th scope="row"><i class="fas fa-file-pdf"></i> 職務経歴書ファイル</th>
          <td><%= link_to "職務経歴書プレビュー", rails_blob_path(@user.career_file, disposition: "career_file") if @user.career_file.attached? %></td>
        </tr>
    
        <tr>
          <th scope="row">自己PR</th>
          <td><%= @user.selfpr %></td>
        </tr>
        
      </tbody>
    </table>
  </div>
</div>