config/routes.rb
Rails.application.routes.draw do
 root to: 'users#index'
 
 get 'signup', to: 'users#new'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
 resources :companies
 resources :recruits, only: [:show, :new, :create, :edit, :update, :destroy]
 resources :members, only: [:show, :new, :create, :edit, :update, :destroy]
 resources :users
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence:true, length: { maximum:50 }
  validate :correct_image_mime_type
  
  has_one_attached :image
  has_many :recruits, dependent: :destroy
  has_many :members, dependent: :destroy
  
  def self.search(search)
    return Company.all unless search
    Company.where(['name LIKE ?', "%#{search}%"])
  end
  
  private
  
  def correct_image_mime_type
    if image.attached? && !image.content_type.in?(%w(image/jpg image/jpeg image/png))
      errors.add(:image, 'を入れて下さい')
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all.page(params[:page]).order('created_at DESC').per(5).search(params[:search])
  end
  
  def new
    @company = Company.new
  end 
  
  def create
    @company = Company.new(company_params)
    
    if @company.save
      flash[:success] = '転職希望者を登録しました。'
      redirect_to @company
    else
      flash.now[:danger] = '転職希望者の登録に失敗しました。'
      render :new
    end
  end
  
  def show
    @company = Company.find(params[:id])
    
    @recruit = @company.recruits.build
    @recruits = @company.recruits.order('created_at DESC').page(params[:page]).per(2)
    
    @member = @company.members.build
    @members = @company.members.order('created_at DESC')
  end
  
  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    
    if @company.update(company_params)
      flash[:success] = '企業情報を更新しました'
      redirect_to @company
    else
      flash.now[:danger] = "企業情報の更新に失敗しました"
      render :edit
    end
      
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    
    flash[:success] = '企業を削除しました。'
    redirect_to "/companies"
  end
  
  private

  def company_params
    params.require(:company).permit(:name, :ceo, :employees, :capital_stock, :headquarter_address, :homepage, :telephone, :established_yearmonth, :image)
  end
  
end

app/views/companies/edit.html.erb
<%= link_to "戻る", @company, class: "btn btn-outline-secondary btn-circle" %>
<h1>企業情報編集</h1>

<%= form_for(@company) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
<div class="card">
  <div class="card-body">
    <h3 class="card-title">基本情報編集</h3><p>* 入力必須項目</p>
    <table class="table">
      <tbody>
        <tr>
          <th style="width:20%">アイコン</th>
          <td>
            <div class="form-group">
          　   <%= f.file_field :image, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th style="width:20%">企業名 *</th>
          <td>
            <div class="form-group">
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">設立年 *</th>
          <td>
            <div class="form-inline col-md-6" id="birthday">
                <%= raw sprintf(
                          f.date_select(
                            :established_yearmonth,
                            {
                              use_month_numbers: true,
                              start_year: 1930,
                              discard_day: true,
                              date_separator: '%s'
                            },
                            { class: 'form-control col-md-3' }
                            ),
                          '年 ') + '月' %>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">代表者名</th>
          <td>
            <%= f.text_field :ceo, class: "form-control" %>
          </td>
        </tr>
        <tr>
          <th scope="row">従業員数</th>
          <td>
            <div class="form-group">
              <%= f.text_field :employees, class: "form-control" %> 人
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">資本金</th>
          <td>
            <div class="form-group">
              <%= f.text_field :capital_stock, class: "form-control" %> 円
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">電話番号</th>
          <td>
            <div class="form-group">
              <%= f.text_field :telephone, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">本社住所</th>
          <td>
            <div class="form-group">
              <%= f.text_field :headquarter_address, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">事業内容</th>
          <td>
            <div class="form-group">
              <%= f.text_area :business_description, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">ホームページ</th>
          <td>  
            <div class="form-group">
              <%= f.text_field :homepage, class: "form-control" %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
  <div class="form-last text-center">
    <%= f.submit '編集', class: "btn btn-outline-primary w-25" %>
  </div>
<% end %>

app/views/companies/index.html.erb
<% if logged_in? %>
<h1>
  企業一覧
  <%= link_to "+ 新規企業登録", new_company_path, class: "btn btn-outline-primary align-items-center col-xs " %>
</h1>

<ul>
  <div class="form-group">
    <%= form_tag(companies_path, :method => 'get' ) do %>
      <%= text_field_tag :search, '', placeholder: "企業名" %>
      <%= submit_tag 'Search', :name => nil, class: 'btn btn-outline-primary' %>
    <% end %>
  </div>
  <% @companies.each do |company| %>
    <li class="card-deck">
      <div class="card">
        <div class="card-body">
          <div class="container">
            <div class="row align-items-center">
              <% if company.image.attached? %>
                <%= image_tag company.image.variant(resize: "64x64!"), class: "img-thumbnail rounded-circle" %>
              <% else %>
                <%= image_tag "/company.png", class: 'img-thumbnail rounded-circle' %>
              <% end %>
              <div class="col-sm">
                <%= company.name %>
              </div>
              <div class="col-sm">
                <%= company.telephone %>
              </div>
              <div class="col-xs">
                <%= link_to "詳細", company_path(company), class: "btn btn-outline-info" %>
                <%= link_to "編集", edit_company_path(company), class: "btn btn-outline-info" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>
  <%= paginate @companies %>
<% else %>
  <%= render "sessions/login_form" %>
<% end %>

app/views/companies/new.html.erb
<%= link_to "戻る", companies_path, class: "btn btn-outline-secondary btn-circle" %>
<h1>新規企業登録</h1>

<%= form_for(@company) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
<div class="card">
  <div class="card-body">
    <h3 class="card-title">基本情報登録</h3><p>* 入力必須項目</p>
    <table class="table">
      <tbody>
        <tr>
          <th style="width:20%">アイコン</th>
          <td>
            <div class="form-group">
          　   <%= f.file_field :image, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th style="width:20%">企業名 *</th>
          <td>
            <div class="form-group">
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">設立年 *</th>
          <td>
            <div class="form-inline col-md-6" id="birthday">
                <%= raw sprintf(
                          f.date_select(
                            :established_yearmonth,
                            {
                              use_month_numbers: true,
                              start_year: 1930,
                              discard_day: true,
                              date_separator: '%s'
                            },
                            { class: 'form-control col-md-3' }
                            ),
                          '年 ') + '月' %>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">代表者名</th>
          <td>
            <%= f.text_field :ceo, class: "form-control" %>
          </td>
        </tr>
        <tr>
          <th scope="row">従業員数</th>
          <td>
            <div class="form-group">
              <%= f.text_field :employees, class: "form-control" %> 人
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">資本金</th>
          <td>
            <div class="form-group">
              <%= f.text_field :capital_stock, class: "form-control" %> 円
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">電話番号</th>
          <td>
            <div class="form-group">
              <%= f.text_field :telephone, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">本社住所</th>
          <td>
            <div class="form-group">
              <%= f.text_field :headquarter_address, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">事業内容</th>
          <td>
            <div class="form-group">
              <%= f.text_area :business_description, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th scope="row">ホームページ</th>
          <td>  
            <div class="form-group">
              <%= f.text_field :homepage, class: "form-control" %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
  <div class="form-last text-center">
    <%= f.submit '登録', class: "btn btn-outline-primary w-25" %>
  </div>
<% end %>

app/views/companies/show.html.erb
<%= link_to "戻る", companies_path, class: "btn btn-outline-secondary btn-circle" %>

<h1>
  企業詳細ページ
  <%= link_to "+ 新規求人情報登録", new_recruit_path(company_id: @company.id), class: "btn btn-outline-primary align-items-center col-xs " %>
  <%= link_to "+ 新規担当者登録", new_member_path(company_id: @company.id), class: "btn btn-outline-primary align-items-center col-xs " %>
  <%= link_to "削除", @company, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn btn-outline-danger' %>
</h1>
<div class="row" id="company-show">
  <div class="col-md-3">
    <h3>企業情報 <%= link_to "編集", edit_company_path(@company), class: "btn btn-outline-primary" %></h3>
    <p>
      <% if @company.image.attached? %>
        <%= image_tag @company.image.variant(resize: "64x64!"), class: "img-thumbnail rounded-circle" %>
      <% else %>
        <%= image_tag "/company.png", class: "img-thumbnail rounded-circle" %>
      <% end %>
    </p>
    <p>
      企業名<br>
      <%= @company.name %>
    </p>
    <p>
      設立<br>
      <% if @company.established_yearmonth.present? %>
        <%= @company.established_yearmonth.strftime('%Y年%m月') %>
      <% end %>
    </p>
    <p>
      代表者<br>
      <%= @company.ceo %>
    </p>
    <p>
      従業員数<br>
      <%= @company.employees %> 名
    </p>
    <p>
      資本金<br>
      <%= @company.capital_stock %> 円
    </p>
    <p>
      電話番号<br>
      <%= @company.telephone %>
    </p>
    <p>
      本社住所<br>
      <%= @company.headquarter_address %>
    </p>
    <p>
      事業内容<br>
      <%= @company.business_description %>
    </p>
    <p>
      ホームページ<br>
      <%= @company.homepage %>
    </p>
  </div>
  
  <div class="col-md-9">
    <h3 class="recruits">求人内容</h3>
    <%= render 'recruits/recruits', recruits: @recruits %>
    
    <h3 class="members">担当者一覧</h3>
    <%= render 'members/members', members: @members %>
  </div>
</div>