config/routes.rb
Rails.application.routes.draw do
 root to: 'users#index'
 
 get 'signup', to: 'users#new'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
 resources :companies
 resources :recruits, only: [:show, :new, :create, :edit, :update, :destroy]
 resources :members, only: [:show, :new, :create, :edit, :update, :destroy]
 resources :users
end

app/models/recruit.rb
class Recruit < ApplicationRecord
  validates :title, presence: true, length: { maximum:25 }
  belongs_to :company
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  def show
    @recruit = Recruit.find(params[:id])
  end
  
  def new
    @company = Company.find(params[:company_id])
    @recruit = Recruit.new(company_id: @company.id)
  end
  
  def create
    @recruit = Recruit.new(recruit_params)
    
    if @recruit.save
      flash[:success] = '新規求人情報を登録しました。'
      redirect_to @recruit
    else
      flash.now[:danger] = '新規求人情報の登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @recruit = Recruit.find(params[:id])
  end

  def update
    @recruit = Recruit.find(params[:id])
    if @recruit.update(recruit_params)
      flash[:success] = "求人情報を更新しました"
      redirect_to @recruit
    else
      flash.now[:danger] = "求人情報の更新に失敗しました"
      render :edit
    end
      
  end

  def destroy
    @recruit = Recruit.find(params[:id])
    @recruit.destroy
    
    flash[:success] = "求人情報を削除しました"
    redirect_to @recruit.company
  end
  
  private
  
  def recruit_params
    params.require(:recruit).permit(:title, :recruitment_background, :job_description, :requirement, :selection_process, :company_id)
  end
end

app/views/recruits/_recruits.html.erb
<ul class="media-list">
  <% recruits.each do |recruit| %>
    <li class="card-deck">
      <div class="card">
        <div class="card-body">
          <div class="container">
            <div class="row align-items-center">
              <div class="col-sm">
                <%= recruit.title %>
              </div>
              <div class="col-xs">
                <%= link_to "詳細", recruit_path(recruit), class: 'btn btn-outline-info' %>
                <%= link_to "削除", recruit, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn btn-outline-danger' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate @recruits %>
</ul>

app/views/recruits/edit.html.erb
<%= link_to "戻る", @recruit, class: "btn btn-outline-secondary btn-circle" %>
<h1>求人情報編集</h1>
<p>* 入力必須項目</p>

<%= form_for(@recruit) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :title, "求人タイトル * (25文字以内)" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :recruitment_background, "募集背景" %>
        <%= f.text_area :recruitment_background, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :job_description, "仕事内容" %>
        <%= f.text_area :job_description, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :requirement, "募集要項" %>
        <%= f.text_area :requirement, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :selection_process, "選考方法" %>
        <%= f.text_area :selection_process, class: "form-control" %>
      </div>
    </div>
  </div>
  <%= f.submit "編集", class: "btn btn-outline-primary" %>
<% end %>

app/views/recruits/new.html.erb
<%= link_to "戻る", @company, class: "btn btn-outline-secondary btn-circle" %>
<h1>新規求人情報登録</h1>
<p>* 入力必須項目</p>

<%= form_for(@recruit) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="row">
    <div class="col-md-12">
      <%= f.hidden_field :company_id %>
      <div class="form-group">
        <%= f.label :title, "求人タイトル * (25文字以内)" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :recruitment_background, "募集背景" %>
        <%= f.text_area :recruitment_background, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :job_description, "仕事内容" %>
        <%= f.text_area :job_description, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :requirement, "募集要項" %>
        <%= f.text_area :requirement, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :selection_process, "選考方法" %>
        <%= f.text_area :selection_process, class: "form-control" %>
      </div>  
    </div>
  </div>
  <%= f.submit '登録', class: "btn btn-outline-primary" %>
<% end %>

app/views/recruits/show.html.erb
<%= link_to "戻る", @recruit.company, class: "btn btn-outline-secondary btn-circle" %>
<h1>
  求人詳細ページ
  <%= link_to "編集", edit_recruit_path(@recruit), class: 'btn btn-outline-info' %>
  <%= link_to "削除", @recruit, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn btn-outline-danger' %>
</h1>

<div class="recruit">
  <h3>求人タイトル</h3>
  <h4><%= @recruit.title %></h4>
  
  <h3>募集背景</h3>
  <p><%= @recruit.recruitment_background %></p><br>
  
  <h3>仕事内容</h3>
  <p><%= @recruit.job_description %></p><br>
  
  <h3>募集要項</h3>
    <table class="table table-bordered" id="recruit">
      <tbody>
        <tr>
          <th style="width:20%"><i class="fas fa-briefcase"></i> 募集職種</th>
          <td>項目１</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-file-alt"></i> 雇用形態</th>
          <td>項目４</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-check"></i> 応募資格</th>
          <td>項目７</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-map-marker-alt"></i> 勤務地</th>
          <td>項目１</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-clock"></i> 勤務時間</th>
          <td>項目４</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-yen-sign"></i> 給与</th>
          <td>項目７</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-heart"></i> 待遇・福利厚生</th>
          <td>項目７</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-calendar-alt"></i> 休暇</th>
          <td>項目７</td>
        </tr>
      </tbody>
    </table>
  
  <h3>選考方法</h3>
    <table class="table table-bordered" id="recruit">
      <tbody>
        <tr>
          <th style="width:20%"><i class="fas fa-envelope"></i> 応募方法</th>
          <td>項目１</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-info-circle"></i> 選考プロセス</th>
          <td>項目４</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-map-marker-alt"></i> 面接地</th>
          <td>項目７</td>
        </tr>
        <tr>
          <th scope="row"><i class="fas fa-user-alt"></i> 担当者</th>
          <td>項目１</td>
        </tr>
      </tbody>
    </table>
</div>