config/routes.rb
Rails.application.routes.draw do
 root to: 'users#index'
 
 get 'signup', to: 'users#new'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
 resources :companies
 resources :recruits, only: [:show, :new, :create, :edit, :update, :destroy]
 resources :members, only: [:show, :new, :create, :edit, :update, :destroy]
 resources :users
end

app/models/member.rb
class Member < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum:50 }
  validates :sex, presence: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum:6, maximum:12 }
  has_secure_password    

  belongs_to :company
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    @member = Member.find(params[:id])
  end
  
  def new
    @company = Company.find(params[:company_id])
    @member = Member.new(company_id: @company.id)
  end

  def create
    @member = Member.new(member_params)
    
    if @member.save
      flash[:success] = '転職希望者を登録しました。'
      redirect_to @member
    else
      flash.now[:danger] = '転職希望者の登録に失敗しました。'
      render :new
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    
    if @member.update(member_params)
      flash[:success] = "担当者情報を更新しました"
      redirect_to @member
    else
      flash.now[:danger] = "担当者情報を更新できませんでした"
      render :edit
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    
    flash[:success] = "担当者を削除しました"
    redirect_back(fallback_location: company_path)
  end
  
  private
  
  def member_params
    params.require(:member).permit(:name, :sex, :telephone, :email, :belonged_company, :company_id, :password, :password_confirmation)
  end
end

app/views/members/_members.html.erb
<ul class="media-list">
  <% members.each do |member| %>
    <li class="card-deck">
      <div class="card">
        <div class="card-body">
          <div class="container">
            <div class="row align-items-center">
              <div class="col-sm">
                <%= member.name %>
              </div>
              <div class="col-xs">
                <%= link_to "詳細", member_path(member), class: 'btn btn-outline-info' %>
                <%= link_to "削除", member, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn btn-outline-danger' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/members/edit.html.erb
<%= link_to "戻る", @member, class: "btn btn-outline-secondary btn-circle" %>
<h1>担当者情報編集</h1>
<p>* 入力必須項目</p>

<%= form_for(@member) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :name, "名前 *" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :sex, '性別 *', class: 'form-label' %><br>
        <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-outline-secondary" style="width:50%">
            <%= f.radio_button :sex, "男性" %> 男性
          </label>
          <label class="btn btn-outline-secondary" style="width:50%">
            <%= f.radio_button :sex, "女性" %> 女性
          </label>
        </div>
      </div>
    
      <div class="form-group">
        <%= f.label :telephone, "電話番号" %>
        <%= f.text_field :telephone, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "メールアドレス *" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :belonged_company, "所属企業" %>
        <%= f.text_field :belonged_company, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード * (6文字以上12文字以下)' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認) *' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
  </div>
  <%= f.submit "編集", class: "btn btn-outline-primary" %>

<% end %>

app/views/members/new.html.erb
<%= link_to "戻る", @company, class: "btn btn-outline-secondary btn-circle" %>
<h1>新規担当者登録</h1>
<p>* 入力必須項目</p>

<%= form_for(@member) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="row">
    <div class="col-md-12">
      <%= f.hidden_field :company_id %>
      <div class="form-group">
        <%= f.label :name, "名前 *" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :sex, '性別 *', class: 'form-label' %><br>
        <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-outline-secondary" style="width:50%">
            <%= f.radio_button :sex, "男性" %> 男性
          </label>
          <label class="btn btn-outline-secondary" style="width:50%">
            <%= f.radio_button :sex, "女性" %> 女性
          </label>
        </div>
      </div>
    
      <div class="form-group">
        <%= f.label :telephone, "電話番号" %>
        <%= f.text_field :telephone, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "メールアドレス *" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :belonged_company, "所属企業" %>
        <%= f.text_field :belonged_company, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :password, 'パスワード * (6文字以上12文字以下)' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認) *' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
    </div>
  </div>
  <%= f.submit '登録', class: "btn btn-outline-primary" %>
<% end %>

app/views/members/show.html.erb
<%= link_to "戻る", @member.company, class: "btn btn-outline-secondary btn-circle" %>
<h1>
  担当者詳細ページ
  <%= link_to "編集", edit_member_path(@member), class: 'btn btn-outline-info' %>
  <%= link_to "削除", @member, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn btn-outline-danger' %>
</h1>

<p>名前：<%= @member.name %></p><br>
<p>性別：<%= @member.sex %></p><br>
<p>電話番号：<%= @member.telephone %></p><br>
<p>メールアドレス：<%= @member.email %></p><br>
<p>所属企業：<%= @member.belonged_company %></p><br>